#!/usr/bin/env bash
#Tell the story of passwd
while IFS=":" read -r f1 f2 f3 f4 f5 f6 f7;
do 
	echo "The user $USERNAME is part of $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $USER_ID_INFO"
done < "/etc/passwd"
