#!/usr/bin/env bash
#Tell the story of passwd
files="/etc/passwd"
while IFS=: read -r f1f2f3f4f5f6f7
do 
	echo "The user $f1 is part of $f4 gang, lives in $f6 and rides $f7.
        $f3's place is protected by the passcode $f2, more info about the user here: $f5"
done < "$files"
