#!/usr/bin/env bash
#Tell the story of passwd
USERNAME="dir"
PASSWORD="dir"
COMMAND="dir"
HOME_DIRECTORY="dir"
GROUP_ID="dir"
USER ID INFO="dir"
USER ID="dir"
while IFS= read -r
do 
	cmd < /etc/passwd | cut -d ';' -f1,2,3,4,5,6,7

	echo -n "The user $USERNAME is part of $GROUP_ID gang."
	echo -n "lives in $HOME_DIRECTORY and rides $COMMAND."
	echo -n "$USER ID's place is protected by the passcode $PASSWORD."
	echo -n "more info about the user here: $USER ID INFO."
done	
