#!/usr/bin/env bash
#To file, or not to file
if [ -e "school" ]
	then 
			echo "school file exists"
if 
		[ ! -e "school" ]
	then 
			echo "school file does not exist"
	else
		[ -s "school" ]
	then 
			echo "school file is empty"
	if 
		[ ! -s "school" ]
			echo " school file is not empty"
if
		[ -f "school" ]
	then 
		echo "school is a regular file"
	fi
		echo "school is not a regular file"
