#!/usr/bin/env bash
#To file, or not to file
if
		[ -e "school" ]
	then 
		echo "school file exists"
if 
		[ -s "school" ]
	then
		echo "school file is empty"
if 	
		[ -f "school" ]
	then
		echo "school is a regular file"
else 
		echo "school file is not empty"
	fi
		echo "school file does not exist"
