#!/usr/bin/env bash
#To file, or not to file
if [ -a "school" ]
	then 
			echo "school file exists"
if 
		[ -s "school" ]
	then 
			echo "school file does not exist"
if 
		[ -e "school" ]
	then 
			echo "school file is empty"
	else 
			echo " school file is not empty"
if
		[ -f "school" ]
	then 
		echo "school is a regular file"
	fi
		echo "school is not a regular file"
